part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const LOGIN = _Paths.LOGIN;
  static const DESHBORD = _Paths.DESHBORD;
  static const HOME = _Paths.HOME;
  static const HOPPINESS = _Paths.HOPPINESS;
  static const ABOUT = _Paths.ABOUT;
  static const MENU = _Paths.MENU;
  static const NOTICE_BOARD = _Paths.NOTICE_BOARD;
  static const NOTICE_BOARD_DETAILS = _Paths.NOTICE_BOARD_DETAILS;
  static const EVENTS = _Paths.EVENTS;
  static const DESHBOARD_SCREEN = _Paths.DESHBOARD_SCREEN;
  static const ASSIGNMENT = _Paths.ASSIGNMENT;
  static const SYLLABUS = _Paths.SYLLABUS;
  static const PDF_VIEW = _Paths.PDF_VIEW;
  static const ACADEMIC_CONTENT = _Paths.ACADEMIC_CONTENT;
  static const UPCOMING_EVENT = _Paths.UPCOMING_EVENT;
  static const MOUNTHWISE_SYLLABUS = _Paths.MOUNTHWISE_SYLLABUS;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const VIDEO_GALLARY = _Paths.VIDEO_GALLARY;
  static const PHOTO_GALLARY = _Paths.PHOTO_GALLARY;
  static const OUR_CAMPUS = _Paths.OUR_CAMPUS;
  static const OUR_PHILOSYPHER = _Paths.OUR_PHILOSYPHER;
  static const ABOUTUS = _Paths.ABOUTUS;
  static const RATE_US = _Paths.RATE_US;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const TERMAND_CONDITION = _Paths.TERMAND_CONDITION;
  static const PHOTO_VIEW = _Paths.PHOTO_VIEW;
  static const CONTECT_US = _Paths.CONTECT_US;
  static const CAMPUS = _Paths.CAMPUS;
  static const ALBUM = _Paths.ALBUM;
  static const HOME_SLIDER_DETAILS = _Paths.HOME_SLIDER_DETAILS;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const FEED = _Paths.FEED;
  static const INTERNAL_REFER_PROGRAM = _Paths.INTERNAL_REFER_PROGRAM;
  static const VIDEO_PLAYER = _Paths.VIDEO_PLAYER;
  static const ARTICAL1 = _Paths.ARTICAL1;
  static const ARTICAL2 = _Paths.ARTICAL2;
  static const ARTICAL3 = _Paths.ARTICAL3;
  static const ARTICAL4 = _Paths.ARTICAL4;
  static const ARTICAL5 = _Paths.ARTICAL5;
  static const ACCEDMIC_CONTENT = _Paths.ACCEDMIC_CONTENT;
  static const TIME_TABLE_SCREEN = _Paths.TIME_TABLE_SCREEN;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const LOGIN = '/login';
  static const DESHBORD = '/deshbord';
  static const HOME = '/home';
  static const HOPPINESS = '/hoppiness';
  static const ABOUT = '/about';
  static const MENU = '/menu';
  static const NOTICE_BOARD = '/notice-board';
  static const NOTICE_BOARD_DETAILS = '/notice-board-details';
  static const EVENTS = '/events';
  static const DESHBOARD_SCREEN = '/deshboard-screen';
  static const ASSIGNMENT = '/assignment';
  static const SYLLABUS = '/syllabus';
  static const PDF_VIEW = '/pdf-view';
  static const ACADEMIC_CONTENT = '/academic-content';
  static const UPCOMING_EVENT = '/upcoming-event';
  static const MOUNTHWISE_SYLLABUS = '/mounthwise-syllabus';
  static const NOTIFICATION = '/notification';
  static const VIDEO_GALLARY = '/video-gallary';
  static const PHOTO_GALLARY = '/photo-gallary';
  static const OUR_CAMPUS = '/our-campus';
  static const OUR_PHILOSYPHER = '/our-philosypher';
  static const ABOUTUS = '/aboutus';
  static const RATE_US = '/rate-us';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const TERMAND_CONDITION = '/termand-condition';
  static const PHOTO_VIEW = '/photo-view';
  static const CONTECT_US = '/contect-us';
  static const CAMPUS = '/campus';
  static const ALBUM = '/album';
  static const HOME_SLIDER_DETAILS = '/home-slider-details';
  static const EDIT_PROFILE = '/edit-profile';
  static const FEED = '/feed';
  static const INTERNAL_REFER_PROGRAM = '/internal-refer-program';
  static const VIDEO_PLAYER = '/video-player';
  static const ARTICAL1 = '/artical1';
  static const ARTICAL2 = '/artical2';
  static const ARTICAL3 = '/artical3';
  static const ARTICAL4 = '/artical4';
  static const ARTICAL5 = '/artical5';
  static const ACCEDMIC_CONTENT = '/accedmic-content';
  static const TIME_TABLE_SCREEN = '/time-table-screen';
}
